name: edp-react-helloworld
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: gcp.edp-epam.com

database:
  required: false


ingress:
  required: false

image:
  name: edp-react-helloworld
  version: latest